### ISSUE TITLE
Use of uninitalized value in WelsVP::VAACalcSadVar_c

### ISSUE THREAD

**Issue by alvestrand** [cisco/openh264#3297]
In Chrome development, we hit this MSAN error (copy of stderr):

STDERR: [OpenH264] this = 0x0x703000041e20, Warning:Change QP Range from(0,51) to (12,42)
STDERR: [OpenH264] this = 0x0x703000041e20, Warning:iNumRefFrame(1) setting does not support the temporal and LTR setting, will be reset to 2
STDERR: ==1==WARNING: MemorySanitizer: use-of-uninitialized-value
STDERR:     #0 0x55da3a306857 in WelsVP::VAACalcSadVar_c(unsigned char const*, unsigned char const*, int, int, int, int*, int*, int*, int*) ./../../third_party/openh264/src/codec/processing/src/vaacalc/vaacalcfuncs.cpp:177:17
STDERR:     #1 0x55da3a31165f in WelsVP::CVAACalculation::Process(int, SPixMap*, SPixMap*) ./../../third_party/openh264/src/codec/processing/src/vaacalc/vaacalculation.cpp:0:0
STDERR:     #2 0x55da3a2ea8e2 in WelsVP::CVpFrameWork::Process(int, SPixMap*, SPixMap*) ./../../third_party/openh264/src/codec/processing/src/common/WelsFrameWork.cpp:169:26

It can be reproduced by compiling Chrome with MSAN and running the "simulcast/h264.html" test from the Web Platform Tests suite.

GN configuration that reproduces the error:

is_component_build = false
is_debug = false
is_msan = true
msan_track_origins = 2
# target_os = "chromeos"
use_goma = true
proprietary_codecs = true
ffmpeg_branding = "Chrome"

Command line that triggers the error:

out/msan/content_shell --run-web-tests third_party/blink/web_tests/external/wpt/webrtc/simulcast/h264.https.html

**Comment by alvestrand** [comment]
Tagging @mzanaty

**Comment by alvestrand** [comment]
There also appears to be the same kind of problem at https://source.chromium.org/chromium/chromium/src/+/master:third_party/openh264/src/codec/processing/src/vaacalc/vaacalcfuncs.cpp;l=85

**Comment by huili2** [comment]
is this issue still existing in latest version?
