### ISSUE TITLE
b52786888ddce9d6bc06b7825ba9bffc65924e0c is leaking

### ISSUE THREAD

**Issue by andywolk** [cisco/openh264#3375]
We have a unit test for mod_openh264 in FreeSWITCH and it started leaking on the latest openh264 library.
Figured out that the issue goes away when reverting https://github.com/cisco/openh264/commit/b52786888ddce9d6bc06b7825ba9bffc65924e0c
The test is here: https://github.com/signalwire/freeswitch/blob/master/src/mod/codecs/mod_openh264/test/test_mod_openh264.cpp
```
=================================================================
==13444==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 6440 byte(s) in 1 object(s) allocated from:
    #0 0x7f1728050d30 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
    #1 0x7f1727ef0887 in WelsCreateDecoder (/usr/local/lib/libopenh264.so.6+0xfd887)
    #2 0x7f17272d354f in switch_core_codec_init_with_bitrate src/switch_core_codec.c:722
    #3 0x55dc5996c2c8 in main test/test_mod_openh264.cpp:143
    #4 0x7f17268ee09a in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 6440 byte(s) in 1 object(s) allocated from:
    #0 0x7f1728050d30 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
    #1 0x7f1727ef0887 in WelsCreateDecoder (/usr/local/lib/libopenh264.so.6+0xfd887)
    #2 0x7f17272d354f in switch_core_codec_init_with_bitrate src/switch_core_codec.c:722
    #3 0x55dc5996bc0e in main test/test_mod_openh264.cpp:78
    #4 0x7f17268ee09a in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 1168 byte(s) in 2 object(s) allocated from:
    #0 0x7f1728050ef0 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xeaef0)
    #1 0x7f1727eed1a1 in WelsDec::CWelsDecoder::CWelsDecoder() (/usr/local/lib/libopenh264.so.6+0xfa1a1)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x7f1728050d30 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
    #1 0x7f1727eed106 in WelsDec::CWelsDecoder::CWelsDecoder() (/usr/local/lib/libopenh264.so.6+0xfa106)

SUMMARY: AddressSanitizer: 14144 byte(s) leaked in 6 allocation(s).
```

**Comment by xiaotiansf** [comment]
Sure, I'll take a look.
