### ISSUE TITLE
Issue 71044: openh264: Fuzzing build failure

### ISSUE THREAD

**Issue by BenzhengZhang** [cisco/openh264#3774]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71044
@tyan0 Could you help check it. Reported after #3723  merged

**Comment by joakim-tjernlund** [comment]
```
Step #1: Collecting corpus-replicator
Step #1:   Downloading https://files.pythonhosted.org/packages/4f/6c/5e73b0839e88392bc7264374a3bdb16e25110369b8c3c26dcaf72728f705/corpus_replicator-1.1.2-py3-none-any.whl (40kB)
Step #1: Collecting PyYAML (from corpus-replicator)
Step #1:   Downloading https://files.pythonhosted.org/packages/54/ed/79a089b6be93607fa5cdaedf301d7dfb23af5f25c398d5ead2525b063e17/pyyaml-6.0.2.tar.gz (130kB)
Step #1:   Installing build dependencies: started
Step #1:   Installing build dependencies: finished with status 'done'
Step #1:   Getting requirements to build wheel: started
Step #1:   Getting requirements to build wheel: finished with status 'done'
Step #1: [91mERROR: Exception:
Step #1: Traceback (most recent call last):
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in main
Step #1:     status = self.run(options, args)
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 345, in run
Step #1:     resolver.resolve(requirement_set)
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
Step #1:     self._resolve_one(requirement_set, req)
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
Step #1:     abstract_dist = self._get_abstract_dist_for(req_to_install)
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 305, in _get_abstract_dist_for
Step #1:     abstract_dist = self.preparer.prepare_linked_requirement(
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 214, in prepare_linked_requirement
Step #1:     abstract_dist.prepare_distribution_metadata(
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_internal/distributions/source.py", line 70, in prepare_distribution_metadata
Step #1:     reqs = self.req.pep517_backend.get_requires_for_build_wheel()
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 70, in get_requires_for_build_wheel
Step #1:     return self._call_hook('get_requires_for_build_wheel', {
Step #1:   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
Step #1:     raise BackendUnavailable
Step #1: pip._vendor.pep517.wrappers.BackendUnavailable
Step #1: [0m[91mWARNING: You are using pip version 19.2.3, however version 24.2 is available.
Step #1: You should consider upgrading via the 'pip install --upgrade pip' command.
Step #1: The command '/bin/sh -c python3 -m pip install corpus-replicator' returned a non-zero code: 2
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 2
```

Isn't that a CI problem?

**Comment by tyan0** [comment]
I think so too. It seems that CI stops at pip before building openh264/decoder_fuzzer.

**Comment by BenzhengZhang** [comment]
Yes, Already reported to [oss-fuzz](https://github.com/google/oss-fuzz)
https://github.com/google/oss-fuzz/issues/12343

**Comment by BenzhengZhang** [comment]
Fixed by https://github.com/google/oss-fuzz/pull/12353
